### PR TITLE
add Storj

### PR DESCRIPTION
**Pull request by kaloyan-raev**

### CODE REVIEW

**Comment by adamsoffer** [comment]
Hey @kaloyan-raev, thanks for the PR! Looks like the endpoint is failing the schema validation check. Can you make sure `Days` & `Revenue` are lowercase?

**Comment by kaloyan-raev** [comment]
@adamsoffer Thanks for looking at this! @grafael updated the endpoint on our side. It should be lowercase now. Could you run the validation again?

**Comment by kaloyan-raev** [comment]
@adamsoffer This change is ready too!

**Comment by adamsoffer** [comment]
Looks good! Just noticed a weird bug with the generated line graph which I fixed on `main`. Can you rebase on `main` and and push up?

**Comment by kaloyan-raev** [comment]
@adamsoffer Rebased.

**Pull request merged**
