### PR TITLE
Update Helium for Solana transition

### PR DESCRIPTION
**Pull request by rawrmaan**
Add Helium's hosted web3index API and remove worker for updating web3index first-party DB.

The new API endpoint combines data from the now-defunct Helium L1 with up-to-date data usage state from Solana via the Dune API.

It's open source and the code is available here: https://github.com/rawrmaan/helium-web3index

This endpoint will likely change in the near future, but the data will stay the same. A new PR will be submitted with the final endpoint.

### CODE REVIEW

**Comment by adamsoffer** [comment]
Thanks @rawrmaan. I see that the demand side fees calculated in this PR are producing drastically different results than what is currently being reported on the site. Could you provide a detailed description of how you're calculating the fees? Additionally, if you believe the current historical reporting of Helium's demand-side fees on the site is inaccurate could you share why? Thanks! 

Frame 1073716850

**Comment by rawrmaan** [comment]
Wait, what? That's not right. This is what I see when I load the chart on https://web3index-60m5ub8e8-livepeer.vercel.app/helium. Not seeing what you're seeing, nor have I ever seen a series like that.

You can verify that the raw data is correct and a continuation of the previous data here: https://helium-web3index.herokuapp.com/

Screenshot 2023-06-10 at 12 42 50 PM

**Comment by adamsoffer** [comment]
@rawrmaan oh dear I'm sorry I had the wrong tab open and was accidentally comparing it with the storj chart 🤦‍♂️ 

This looks good to me! Thanks so much for the contribution.

**Review by adamsoffer — APPROVED** [review]
🙏

**Pull request merged**
